# Generated by Django 5.2.4 on 2025-08-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminders", "0002_reminderlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reminder",
            name="timer",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="reminder",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
