# Generated by Django 5.2.4 on 2025-08-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminders", "0003_remove_reminder_timer_remove_reminder_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="timer",
            field=models.IntegerField(default=30),
        ),
    ]
