# Generated by Django 5.2.4 on 2025-08-03 07:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminders", "0004_reminder_timer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="timer",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("30.00"), max_digits=5
            ),
        ),
    ]
